-- ============================================================
-- 005_wellness_plans.sql
-- Personalised wellness plans generated by the engine
-- ============================================================

CREATE TABLE wellness_plans (
  id                        UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id                   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  generated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  framework_ids             TEXT[] NOT NULL DEFAULT '{}',
  diet_adjustments          JSONB NOT NULL DEFAULT '[]',
  lifestyle_adjustments     JSONB NOT NULL DEFAULT '[]',
  mindset_recommendations   JSONB NOT NULL DEFAULT '[]',
  supplement_suggestions    JSONB NOT NULL DEFAULT '[]',
  is_active                 BOOLEAN NOT NULL DEFAULT TRUE,
  version                   INTEGER NOT NULL DEFAULT 1,
  created_at                TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE wellness_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own wellness plans"
  ON wellness_plans FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Service role can insert wellness plans"
  ON wellness_plans FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- When a new plan is generated, deactivate previous plans
CREATE OR REPLACE FUNCTION deactivate_previous_plans()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE wellness_plans
  SET is_active = FALSE
  WHERE user_id = NEW.user_id
    AND id != NEW.id
    AND is_active = TRUE;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER deactivate_old_plans
  AFTER INSERT ON wellness_plans
  FOR EACH ROW EXECUTE FUNCTION deactivate_previous_plans();

CREATE INDEX idx_wellness_plans_user_active
  ON wellness_plans(user_id, is_active)
  WHERE is_active = TRUE;

CREATE TRIGGER wellness_plans_audit
  AFTER INSERT OR UPDATE OR DELETE ON wellness_plans
  FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();
