-- ============================================================
-- 021_geo_restrictions_all_countries.sql
-- Extend geo_restrictions (018) to cover every country in the world,
-- not just the original 24-market shortlist.
--
-- All new rows default to 'disabled' / enabled=FALSE — the admin must
-- explicitly open each market, same convention as 018. ON CONFLICT DO
-- NOTHING protects the 24 countries already configured (and their
-- admin-set mode) from being reset.
-- ============================================================

INSERT INTO geo_restrictions (country_code, country_name, mode, enabled) VALUES
  ('AF', 'Afghanistan',                          'disabled', FALSE),
  ('AL', 'Albania',                              'disabled', FALSE),
  ('DZ', 'Algeria',                              'disabled', FALSE),
  ('AD', 'Andorra',                              'disabled', FALSE),
  ('AO', 'Angola',                               'disabled', FALSE),
  ('AG', 'Antigua and Barbuda',                  'disabled', FALSE),
  ('AR', 'Argentina',                            'disabled', FALSE),
  ('AM', 'Armenia',                              'disabled', FALSE),
  ('AT', 'Austria',                              'disabled', FALSE),
  ('AZ', 'Azerbaijan',                           'disabled', FALSE),
  ('BS', 'Bahamas',                              'disabled', FALSE),
  ('BH', 'Bahrain',                              'disabled', FALSE),
  ('BD', 'Bangladesh',                           'disabled', FALSE),
  ('BB', 'Barbados',                             'disabled', FALSE),
  ('BY', 'Belarus',                              'disabled', FALSE),
  ('BE', 'Belgium',                              'disabled', FALSE),
  ('BZ', 'Belize',                               'disabled', FALSE),
  ('BJ', 'Benin',                                'disabled', FALSE),
  ('BT', 'Bhutan',                               'disabled', FALSE),
  ('BO', 'Bolivia',                              'disabled', FALSE),
  ('BA', 'Bosnia and Herzegovina',                'disabled', FALSE),
  ('BW', 'Botswana',                             'disabled', FALSE),
  ('BR', 'Brazil',                               'disabled', FALSE),
  ('BN', 'Brunei',                               'disabled', FALSE),
  ('BG', 'Bulgaria',                             'disabled', FALSE),
  ('BF', 'Burkina Faso',                         'disabled', FALSE),
  ('BI', 'Burundi',                              'disabled', FALSE),
  ('CV', 'Cabo Verde',                           'disabled', FALSE),
  ('KH', 'Cambodia',                             'disabled', FALSE),
  ('CM', 'Cameroon',                             'disabled', FALSE),
  ('CF', 'Central African Republic',              'disabled', FALSE),
  ('TD', 'Chad',                                 'disabled', FALSE),
  ('CL', 'Chile',                                'disabled', FALSE),
  ('CN', 'China',                                'disabled', FALSE),
  ('CO', 'Colombia',                             'disabled', FALSE),
  ('KM', 'Comoros',                              'disabled', FALSE),
  ('CG', 'Congo',                                'disabled', FALSE),
  ('CD', 'Congo (DRC)',                          'disabled', FALSE),
  ('CR', 'Costa Rica',                           'disabled', FALSE),
  ('CI', 'Côte d''Ivoire',                       'disabled', FALSE),
  ('HR', 'Croatia',                              'disabled', FALSE),
  ('CU', 'Cuba',                                 'disabled', FALSE),
  ('CY', 'Cyprus',                               'disabled', FALSE),
  ('CZ', 'Czechia',                              'disabled', FALSE),
  ('DJ', 'Djibouti',                             'disabled', FALSE),
  ('DM', 'Dominica',                             'disabled', FALSE),
  ('DO', 'Dominican Republic',                   'disabled', FALSE),
  ('EC', 'Ecuador',                              'disabled', FALSE),
  ('EG', 'Egypt',                                'disabled', FALSE),
  ('SV', 'El Salvador',                          'disabled', FALSE),
  ('GQ', 'Equatorial Guinea',                    'disabled', FALSE),
  ('ER', 'Eritrea',                              'disabled', FALSE),
  ('EE', 'Estonia',                              'disabled', FALSE),
  ('SZ', 'Eswatini',                             'disabled', FALSE),
  ('ET', 'Ethiopia',                             'disabled', FALSE),
  ('FJ', 'Fiji',                                 'disabled', FALSE),
  ('FI', 'Finland',                              'disabled', FALSE),
  ('GA', 'Gabon',                                'disabled', FALSE),
  ('GM', 'Gambia',                               'disabled', FALSE),
  ('GE', 'Georgia',                              'disabled', FALSE),
  ('GR', 'Greece',                               'disabled', FALSE),
  ('GD', 'Grenada',                              'disabled', FALSE),
  ('GT', 'Guatemala',                            'disabled', FALSE),
  ('GN', 'Guinea',                               'disabled', FALSE),
  ('GW', 'Guinea-Bissau',                        'disabled', FALSE),
  ('GY', 'Guyana',                               'disabled', FALSE),
  ('HT', 'Haiti',                                'disabled', FALSE),
  ('VA', 'Holy See',                             'disabled', FALSE),
  ('HN', 'Honduras',                             'disabled', FALSE),
  ('HU', 'Hungary',                              'disabled', FALSE),
  ('IS', 'Iceland',                              'disabled', FALSE),
  ('ID', 'Indonesia',                            'disabled', FALSE),
  ('IR', 'Iran',                                 'disabled', FALSE),
  ('IQ', 'Iraq',                                 'disabled', FALSE),
  ('IL', 'Israel',                               'disabled', FALSE),
  ('JM', 'Jamaica',                              'disabled', FALSE),
  ('JP', 'Japan',                                'disabled', FALSE),
  ('JO', 'Jordan',                               'disabled', FALSE),
  ('KZ', 'Kazakhstan',                           'disabled', FALSE),
  ('KI', 'Kiribati',                             'disabled', FALSE),
  ('KW', 'Kuwait',                               'disabled', FALSE),
  ('KG', 'Kyrgyzstan',                           'disabled', FALSE),
  ('LA', 'Laos',                                 'disabled', FALSE),
  ('LV', 'Latvia',                               'disabled', FALSE),
  ('LB', 'Lebanon',                              'disabled', FALSE),
  ('LS', 'Lesotho',                              'disabled', FALSE),
  ('LR', 'Liberia',                              'disabled', FALSE),
  ('LY', 'Libya',                                'disabled', FALSE),
  ('LI', 'Liechtenstein',                        'disabled', FALSE),
  ('LT', 'Lithuania',                            'disabled', FALSE),
  ('LU', 'Luxembourg',                           'disabled', FALSE),
  ('MG', 'Madagascar',                           'disabled', FALSE),
  ('MW', 'Malawi',                               'disabled', FALSE),
  ('MY', 'Malaysia',                             'disabled', FALSE),
  ('MV', 'Maldives',                             'disabled', FALSE),
  ('ML', 'Mali',                                 'disabled', FALSE),
  ('MT', 'Malta',                                'disabled', FALSE),
  ('MH', 'Marshall Islands',                     'disabled', FALSE),
  ('MR', 'Mauritania',                           'disabled', FALSE),
  ('MU', 'Mauritius',                            'disabled', FALSE),
  ('MX', 'Mexico',                               'disabled', FALSE),
  ('FM', 'Micronesia',                           'disabled', FALSE),
  ('MD', 'Moldova',                              'disabled', FALSE),
  ('MC', 'Monaco',                               'disabled', FALSE),
  ('MN', 'Mongolia',                             'disabled', FALSE),
  ('ME', 'Montenegro',                           'disabled', FALSE),
  ('MA', 'Morocco',                              'disabled', FALSE),
  ('MZ', 'Mozambique',                           'disabled', FALSE),
  ('MM', 'Myanmar',                              'disabled', FALSE),
  ('NA', 'Namibia',                              'disabled', FALSE),
  ('NR', 'Nauru',                                'disabled', FALSE),
  ('NP', 'Nepal',                                'disabled', FALSE),
  ('NI', 'Nicaragua',                            'disabled', FALSE),
  ('NE', 'Niger',                                'disabled', FALSE),
  ('KP', 'North Korea',                          'disabled', FALSE),
  ('MK', 'North Macedonia',                      'disabled', FALSE),
  ('OM', 'Oman',                                 'disabled', FALSE),
  ('PK', 'Pakistan',                             'disabled', FALSE),
  ('PW', 'Palau',                                'disabled', FALSE),
  ('PS', 'Palestine',                            'disabled', FALSE),
  ('PA', 'Panama',                               'disabled', FALSE),
  ('PG', 'Papua New Guinea',                     'disabled', FALSE),
  ('PY', 'Paraguay',                             'disabled', FALSE),
  ('PE', 'Peru',                                 'disabled', FALSE),
  ('PH', 'Philippines',                          'disabled', FALSE),
  ('PL', 'Poland',                               'disabled', FALSE),
  ('PT', 'Portugal',                             'disabled', FALSE),
  ('QA', 'Qatar',                                'disabled', FALSE),
  ('RO', 'Romania',                              'disabled', FALSE),
  ('RU', 'Russia',                               'disabled', FALSE),
  ('RW', 'Rwanda',                               'disabled', FALSE),
  ('KN', 'Saint Kitts and Nevis',                'disabled', FALSE),
  ('LC', 'Saint Lucia',                          'disabled', FALSE),
  ('VC', 'Saint Vincent and the Grenadines',      'disabled', FALSE),
  ('WS', 'Samoa',                                'disabled', FALSE),
  ('SM', 'San Marino',                           'disabled', FALSE),
  ('ST', 'São Tomé and Príncipe',                'disabled', FALSE),
  ('SA', 'Saudi Arabia',                         'disabled', FALSE),
  ('SN', 'Senegal',                              'disabled', FALSE),
  ('RS', 'Serbia',                               'disabled', FALSE),
  ('SC', 'Seychelles',                           'disabled', FALSE),
  ('SL', 'Sierra Leone',                         'disabled', FALSE),
  ('SK', 'Slovakia',                             'disabled', FALSE),
  ('SI', 'Slovenia',                             'disabled', FALSE),
  ('SB', 'Solomon Islands',                      'disabled', FALSE),
  ('SO', 'Somalia',                              'disabled', FALSE),
  ('KR', 'South Korea',                          'disabled', FALSE),
  ('SS', 'South Sudan',                          'disabled', FALSE),
  ('LK', 'Sri Lanka',                            'disabled', FALSE),
  ('SD', 'Sudan',                                'disabled', FALSE),
  ('SR', 'Suriname',                             'disabled', FALSE),
  ('SY', 'Syria',                                'disabled', FALSE),
  ('TW', 'Taiwan',                               'disabled', FALSE),
  ('TJ', 'Tajikistan',                           'disabled', FALSE),
  ('TZ', 'Tanzania',                             'disabled', FALSE),
  ('TH', 'Thailand',                             'disabled', FALSE),
  ('TL', 'Timor-Leste',                          'disabled', FALSE),
  ('TG', 'Togo',                                 'disabled', FALSE),
  ('TO', 'Tonga',                                'disabled', FALSE),
  ('TT', 'Trinidad and Tobago',                  'disabled', FALSE),
  ('TN', 'Tunisia',                              'disabled', FALSE),
  ('TR', 'Türkiye',                              'disabled', FALSE),
  ('TM', 'Turkmenistan',                         'disabled', FALSE),
  ('TV', 'Tuvalu',                               'disabled', FALSE),
  ('UA', 'Ukraine',                              'disabled', FALSE),
  ('UY', 'Uruguay',                              'disabled', FALSE),
  ('UZ', 'Uzbekistan',                           'disabled', FALSE),
  ('VU', 'Vanuatu',                              'disabled', FALSE),
  ('VE', 'Venezuela',                            'disabled', FALSE),
  ('VN', 'Vietnam',                              'disabled', FALSE),
  ('YE', 'Yemen',                                'disabled', FALSE),
  ('ZW', 'Zimbabwe',                             'disabled', FALSE)
ON CONFLICT (country_code) DO NOTHING;
